### ISSUE TITLE
Extensibility of functions

### ISSUE THREAD

**Issue by OlafConijn** [gristlabs/yaml-cfn#10]
Hi!

I would like to extend the yaml-cfn library to add my own tags (and extend cloudformation - sounds crazy, i know!). Would this be possible? for now I had to include your source in my project, which is less than ideal. thanks a lot!

Olaf

**Comment by dsagal** [comment]
The `yaml-cfn` library is very simple. To make it extensible would require some changes to the interface. You are welcome to submit a PR, but copying the code might not be so bad in this case.

**Comment by OlafConijn** [comment]
that's what i figured. thanks!
