### ISSUE TITLE
Please support Fn::Cidr

### ISSUE THREAD

**Issue by michael-crawford** [gristlabs/yaml-cfn#4]
Templates containing Fn::Cidr break.

This seems easy to fix, below line line 72 of index.js, add:
  'Fn::Cidr',

I have never tried to create a formal pull request for another project, so I wanted to report this first. If I have time to research how to do this and create a pull request for you, I will do so, but you may get to this quicker than I can.

This is also missing support for Fn::Transform, but as I'm not using that, I don't have a way to test that potential fix, not sure if it's just as simple.

**Comment by michael-crawford** [comment]
Created a pull request - first time, hopefully I've done this correctly!

Please let me know if you can get this fix applied and then update the package in npm.

Also, thanks for creating this - using this to parse CFN YAML into JSON and extract Parameters, look for Lambda functions, etc. Very useful!

**Comment by gabegorelick** [comment]
This was fixed in 0.2.1.

**Comment by johnbeech** [comment]
This issue looks like it can be closed, see: #5
