### ISSUE TITLE
PolicyDocument Version field is read as a date instead of a string

### ISSUE THREAD

**Issue by jamestelfer** [gristlabs/yaml-cfn#8]
If you import a CFN file that include a role definition with inline policies, the `Version` field of the `PolicyDocument` is interpreted as a `Date` rather than a `String`.

If the file is then written out, it changes `"2012-10-17"` to `"2012-10-17T00:00:00.000Z"`.

AFAICT, this is because the CFN schema depends on the js-yaml `SAFE_SCHEMA`, which defines a timestamp type. This implicit type matches any string that looks like it conforms to a YAML date, and converts it to a JS `Date` object.

According to the AWS documentation for the [Cloudformation file formats](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html), the YAML dialect doesn't support the full gamut of YAML 1.1.

> AWS CloudFormation supports the YAML Version 1.1 specification with a few exceptions. AWS CloudFormation doesn't support the following features:
>
> * The binary, omap, pairs, set, and timestamp tags
> * Aliases
> * Hash merges

In order to work around this temporarily, I created a new schema that included the yaml-cfn schema, and added an implicit type for the tag `'tag:yaml.org,2002:timestamp'`. This implicit type used js-yaml's `resolve` function, but used the identity function for `construct` and `represent`. This is a dirty hack however.

It would appear thought that basing the CFN schema on `CORE_SCHEMA` instead would yield the desired result, as that excludes all of the items listed in the documentation except for aliases.

**Comment by dsagal** [comment]
Isn't it true that a quoted `"2012-10-17"` is maintained as the string `"2012-10-17"`, and only unquoted dates are parsed? In other words, a simple workaround is available: to quote the dates.

That's why it hasn't been a serious problem, but I agree that it's a frequent annoyance. Your proposal to fix it sounds good.

**Comment by jamestelfer** [comment]
You’re quite right: I found this when creating the test case and meant to comment. 

Still, I appreciate your response. This will make using the schema more frictionless. 

Thanks!
